import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Alphabyte Innovation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen" style={{ paddingTop: "25px" }}>
        {/* Navbar */}
        <div className="navbar bg-white fixed top-0 w-full z-50">
          <div className="navbar-start">
            <img src="/logo.png" alt="Alphabyte Logo" className="h-10 w-10" />
            <a className="text-2xl ml-1 text-black">ALPHABYTE in</a>
          </div>
          <div className="navbar-end">
            <ul className="menu menu-horizontal text-black text-1xl px-1 font-bold my-2.5 mr-14">
              <li className="mr-6">
                <Link href="/">Home</Link>
              </li>
              <li className="mr-6">
                <Link href="/project">Project</Link>
              </li>
              <li className="mr-6">
                <Link href="/about">About Us</Link>
              </li>
            </ul>
          </div>
        </div>

        {/* Page Content */}
        <div className="flex-grow" style={{ marginTop: "60px" }}>
          {children}
        </div>

        {/* Footer */}
        <footer className="footer sm:footer-horizontal bg-white text-neutral-content items-center p-4">
          <aside className="grid-flow-col items-center">
            <svg
              width="36"
              height="36"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
              fillRule="evenodd"
              clipRule="evenodd"
              className="fill-current"
            >
              <path d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"></path>
            </svg>
            <p className="text-black">
              Copyright © {new Date().getFullYear()} - Alphabyte reserved
            </p>
          </aside>
          <nav className="grid-flow-col gap-4 md:place-self-center md:justify-self-end text-black">
            <a
              href="https://www.linkedin.com/in/your-profile"
              target="_blank"
              rel="noopener noreferrer"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                className="fill-current"
              >
                <path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.761 0 5-2.239 5-5v-14c0-2.761-2.239-5-5-5zm-11 19h-3v-10h3v10zm-1.5-11.268c-.966 0-1.75-.784-1.75-1.75s.784-1.75 1.75-1.75 1.75.784 1.75 1.75-.784 1.75-1.75 1.75zm13.5 11.268h-3v-5.604c0-1.337-.026-3.063-1.867-3.063-1.868 0-2.155 1.459-2.155 2.967v5.7h-3v-10h2.881v1.367h.041c.401-.759 1.379-1.559 2.841-1.559 3.038 0 3.6 2.001 3.6 4.604v5.588z"></path>
              </svg>
            </a>
          </nav>
        </footer>
      </body>
    </html>
  );
}